services:

############################################################ MQTT

  mosquitto:
    image: eclipse-mosquitto
    container_name: mqtt
    ports:
      - 1883:1883
      - 9001:9001
    restart: unless-stopped
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log

############################################################ Python

  python-app:
    container_name: python
    build: .
    command: "python -u client_sub.py ${UPLOAD} ${IP}"
    volumes:
      - ./python/data:/usr/src/app/python/data
    env_file: .env